"""empty message
Revision ID: 49df8e610d33
Revises: 81d804b1c18c
Create Date: 2025-06-21 23:24:05.447521

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "49df8e610d33"
down_revision = "81d804b1c18c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "template", sa.String(), server_default="post.html", nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_column("template")

    # ### end Alembic commands ###
