"""conflict

Revision ID: 7bc06f2fee58
Revises: 027b40980791
Create Date: 2024-04-29 10:49:43.269179

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7bc06f2fee58"
down_revision = "027b40980791"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.alter_column(
            "bg", existing_type=sa.VARCHAR(length=255), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.alter_column("bg", existing_type=sa.VARCHAR(length=255), nullable=True)

    # ### end Alembic commands ###
