"""empty message

Revision ID: b7b6e253e6fb
Revises: eead387d732e
Create Date: 2025-11-09 20:58:03.081802

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b7b6e253e6fb"
down_revision = "eead387d732e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.add_column(sa.Column("page", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_column("page")

    # ### end Alembic commands ###
