"""empty message

Revision ID: eead387d732e
Revises: f00000000002
Create Date: 2025-11-09 20:49:44.655909

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eead387d732e"
down_revision = "f00000000002"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.alter_column(
            "title", existing_type=sa.VARCHAR(length=255), nullable=True
        )
        batch_op.alter_column(
            "alias", existing_type=sa.VARCHAR(length=255), nullable=True
        )

    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.alter_column("createdon", existing_type=sa.DATETIME(), nullable=True)

    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.alter_column(
            "title", existing_type=sa.VARCHAR(length=255), nullable=True
        )
        batch_op.alter_column(
            "alias", existing_type=sa.VARCHAR(length=255), nullable=True
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "createdon",
            existing_type=sa.DATETIME(),
            nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "createdon",
            existing_type=sa.DATETIME(),
            nullable=False,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )

    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.alter_column(
            "alias", existing_type=sa.VARCHAR(length=255), nullable=False
        )
        batch_op.alter_column(
            "title", existing_type=sa.VARCHAR(length=255), nullable=False
        )

    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.alter_column("createdon", existing_type=sa.DATETIME(), nullable=False)

    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.alter_column(
            "alias", existing_type=sa.VARCHAR(length=255), nullable=False
        )
        batch_op.alter_column(
            "title", existing_type=sa.VARCHAR(length=255), nullable=False
        )

    # ### end Alembic commands ###
