"""empty message

Revision ID: f3dc69141caf
Revises: 81e84d7978cc
Create Date: 2022-01-23 22:52:06.146299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3dc69141caf'
down_revision = '81e84d7978cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('alias', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'tags', ['alias'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_column('tags', 'alias')
    # ### end Alembic commands ###
